export const SEND_OTP = 'user/generate-otp-temp'
export const VERIFY_OTP = 'user/validate-otp-with-temp-token'
export const RESET_PASSWORD = 'user/reset-password-with-temp-token'
// export const LEGACY_LOGIN = 'v1/auth/login'  renamed  '/v2/auth/login'
export const LEGACY_LOGIN = 'v2/auth/login'
